using System.Text.Json.Serialization;
using Poloniex.Net.Objects.Internal;
using Poloniex.Net.Objects.Models;
using CryptoExchange.Net.Objects;

namespace Poloniex.Net.Converters
{
    [JsonSerializable(typeof(PoloniexTimestamp))]
    [JsonSerializable(typeof(PoloniexAccount[]))]
    [JsonSerializable(typeof(PoloniexAccountBalance[]))]
    [JsonSerializable(typeof(PoloniexCurrency[]))]
    [JsonSerializable(typeof(PoloniexSymbol[]))]
    [JsonSerializable(typeof(PoloniexTicker))]
    [JsonSerializable(typeof(PoloniexTicker[]))]
    [JsonSerializable(typeof(PoloniexFuturesRestResult<PoloniexFuturesInstrument[]>))]
    [JsonSerializable(typeof(PoloniexFuturesRestResult<PoloniexFuturesTicker[]>))]
    [JsonSerializable(typeof(PoloniexFuturesRestResult<PoloniexFuturesFundingRate>))]
    [JsonSerializable(typeof(PoloniexFuturesRestResult<PoloniexFuturesAccountBalance>))]
    [JsonSerializable(typeof(PoloniexFuturesRestResult<PoloniexFuturesBill[]>))]
    [JsonSerializable(typeof(PoloniexFuturesRestResult<PoloniexFuturesPositionModeInfo>))]
    [JsonSerializable(typeof(PoloniexFuturesRestResult<PoloniexFuturesLeverage>))]
    [JsonSerializable(typeof(PoloniexFuturesRestResult<PoloniexFuturesLeverage[]>))]
    [JsonSerializable(typeof(PoloniexFuturesRestResult<PoloniexFuturesOrderId>))]
    [JsonSerializable(typeof(PoloniexFuturesRestResult<PoloniexFuturesOrder>))]
    [JsonSerializable(typeof(PoloniexFuturesRestResult<PoloniexFuturesOrder[]>))]
    [JsonSerializable(typeof(PoloniexFuturesRestResult<PoloniexFuturesOrderTrade[]>))]
    [JsonSerializable(typeof(PoloniexFuturesRestResult<PoloniexFuturesPosition[]>))]
    [JsonSerializable(typeof(PoloniexFuturesRestResult<PoloniexFuturesPositionHistory[]>))]
    [JsonSerializable(typeof(PoloniexFuturesRestResult<object>))]
    [JsonSerializable(typeof(PoloniexAccountFee))]
    [JsonSerializable(typeof(PoloniexSocketRequest))]
    [JsonSerializable(typeof(PoloniexSocketResponse<PoloniexSocketAuthResponse>))]
    [JsonSerializable(typeof(PoloniexSocketSubscriptionResponse))]
    [JsonSerializable(typeof(PoloniexSubscriptionEvent<PoloniexOrderBook>))]
    [JsonSerializable(typeof(PoloniexSubscriptionEvent<PoloniexTrade>))]
    [JsonSerializable(typeof(PoloniexSubscriptionEvent<PoloniexTicker>))]
    [JsonSerializable(typeof(PoloniexSubscriptionEvent<PoloniexFuturesTrade>))]
    [JsonSerializable(typeof(PoloniexSubscriptionEvent<PoloniexFuturesTicker>))]
    [JsonSerializable(typeof(PoloniexSubscriptionEvent<PoloniexFuturesIndexPrice>))]
    [JsonSerializable(typeof(PoloniexSubscriptionEvent<PoloniexFuturesFundingRate>))]
    [JsonSerializable(typeof(PoloniexSubscriptionEvent<PoloniexFuturesAccountBalance>))]
    [JsonSerializable(typeof(PoloniexSubscriptionEvent<PoloniexFuturesOrder>))]
    [JsonSerializable(typeof(PoloniexSubscriptionEvent<PoloniexFuturesOrderTrade>))]
    [JsonSerializable(typeof(PoloniexSubscriptionEvent<PoloniexFuturesPosition>))]
    [JsonSerializable(typeof(PoloniexSubscriptionEvent<PoloniexCandle>))]
    [JsonSerializable(typeof(PoloniexSubscriptionEvent<PoloniexOrderUpdate>))]
    [JsonSerializable(typeof(PoloniexSubscriptionEvent<PoloniexBalanceUpdate>))]
    [JsonSerializable(typeof(IDictionary<string, object>))]
    [JsonSerializable(typeof(int?))]
    [JsonSerializable(typeof(PoloniexOrderId))]
    [JsonSerializable(typeof(PoloniexCancelOrderResult))]
    [JsonSerializable(typeof(PoloniexOrder[]))]
    [JsonSerializable(typeof(PoloniexOrderTrade[]))]
    [JsonSerializable(typeof(PoloniexAccountTransfer))]
    [JsonSerializable(typeof(PoloniexWalletActivity))]
    [JsonSerializable(typeof(PoloniexAccountActivity[]))]
    [JsonSerializable(typeof(Parameters))]
    internal partial class PoloniexSourceGenerationContext : JsonSerializerContext
    { }
}
